services:
  - type: web
    name: phikita-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      PYTHON_VERSION: 3.11.9